### ISSUE TITLE
Integration in the Bookcreator-Plugin

### ISSUE THREAD

**Issue by Nos-** [turnermm/epub#19]
Hi,
thanks for the epub-exportfunctionality.

What do you think about an integration of this plugin in Dokuwiki's bookcreater-Plugin? Many users would benefit from it i think. And of course more user would get notice of your plugin.

**Comment by turnermm** [comment]
I've never used the bookcreator plugin.  The  epub plugin does create a book -- an ebook of all  the pages selected, so this seems to me to be a bit  of duplication.  But if you think there is some advantage to adapting epub to bookcreator, you are welcome to fork a copy of epub and make the integration.

**Comment by Nos-** [comment]
Thanks for your quick answer.
I use the mentioned bookcreator-plugin since some time to have an exportfunctionality for several exportformats at one place. As you wrote two bookexportplugins are a kind of duplication therefore my request to integrate these two plugins into each other.
