### ISSUE TITLE
Exclude page from namespace

### ISSUE THREAD

**Issue by typometre** [turnermm/epub#27]
Hi.
Thanks for the plugin.
I tried to use it to build an ePub export out of a regularly updated namespace.
The namespace option is really nice for that as there is no need to list each page but I can't find a way to exclude some page (as start, sidebar, or _template) which are purely technical and doesn't have to be in the generated ePub.
Is there a synthax t append to namespace to exclude certain pages ?
Best regards

**Comment by turnermm** [comment]
> Is  there a synthax t append to namespace to exclude certain pages ?

Afraid not
