### ISSUE TITLE
"Warning: Declaration of renderer_plugin_epub::header ..." and "Warning: Cannot modify header information"

### ISSUE THREAD

**Issue by eduardomozart** [turnermm/epub#36]
Hello,

After upgrading to DokuWiki Release 2022-07-31 "Igor", I'd started receiving the following error when I access the built-in DokuWiki's Configuration Manager:

```
Warning: Declaration of renderer_plugin_epub::header($text, $level, $pos) should be compatible with Doku_Renderer_xhtml::header($text, $level, $pos, $returnonly = false) in /home/eduardo/public_html/wiki/lib/plugins/epub/renderer.php on line 94

Warning: Cannot modify header information - headers already sent by (output started at /home/eduardo/public_html/wiki/lib/plugins/epub/renderer.php:473) in /home/eduardo/public_html/wiki/inc/actions.php on line 38
```

The issue persists after upgrading to DokuWiki Release 2022-07-31a "Igor".

Please let me know if anymore information are needed to troubleshoot this issue.

**Comment by eduardomozart** [comment]
It seems that you're already concerned about this issue https://github.com/turnermm/epub/commit/2f8ebb0e9b1dcbd2a3340d401b2e413e4390e298, but the plugin wasn't updated into the DokuWiki Plugins page - https://www.dokuwiki.org/plugin:epub

**Comment by turnermm** [comment]
Thanks. I'll try to get to it tomorrow

**Comment by turnermm** [comment]
Done.  I got to it tonight

**Comment by eduardomozart** [comment]
I can confirm that the plugin was updated at the DokuWiki plugin page and the updated version is already available for installing at Extension Manager and it's working just fine. Thank you for your good working at this extension @turnermm!
